CREATE PROCEDURE [DBO].[ABC_UPDATELANMU_ISIN]                
               
   @DOCDATE  DATETIME,                
   @DOCCODE VARCHAR(16),                
   @FORM_ID VARCHAR(20),        
   @RESULT NVARCHAR(50) OUTPUT        
AS                
          
            
IF ISNULL(@FORM_ID,'')='11-111'            
BEGIN            
            
 INSERT INTO HRPUTMONEYDATA(IKEY,PARENT_IKEY,PERIODID,ATTDATE,COMPANYID,HRROWID,HRCODE,HRNAME,ADMINDPT,DOCCODE,DEPARTMENTID,PUTTYPE,ISIN,PUTMONEY,ITEMNAME,PERIODTYPE,FORM_ID,CREATE_NAME,UPDATE_NAME,POST_USERNAME)              
 SELECT   HRBUSIDOCITEM.IKEY,PARENT_IKEY,CONVERT(VARCHAR(7),@DOCDATE,120),@DOCDATE,HRBUSIDOCHD.COMPANYID,HRROWID,HRCODE,HRNAME,ADMINDPT,@DOCCODE,DPTID2,PUTTYPE,0,          
    PUTMONEY=(CASE PUTISIN WHEN '罚' THEN -PUTMONEY ELSE PUTMONEY END),'奖惩','标准期间' ,FORM_ID,HRBUSIDOCHD.CREATE_NAME,HRBUSIDOCHD.UPDATE_NAME,HRBUSIDOCHD.POST_USERNAME          
  FROM HRBUSIDOCHD LEFT OUTER JOIN HRBUSIDOCITEM ON HRBUSIDOCHD.DOCCODE=HRBUSIDOCITEM.DOCCODE            
  WHERE HRBUSIDOCHD.DOCCODE=@DOCCODE            
            
END            
          
-----------------------------------            
            
IF ISNULL(@FORM_ID,'')='11-112'            
BEGIN            
        
  IF EXISTS(SELECT * FROM HRBUSIDOCITEM WHERE DOCCODE=@DOCCODE AND ISNULL(DPTID2,'')='')            
  BEGIN            
   RAISERROR('入帐部门未填写，请检查！',16,1)            
   RETURN            
  END            
          
IF EXISTS(SELECT * FROM (SELECT DPTID2,SUM(CASE PUTISIN WHEN '罚' THEN -PUTMONEY ELSE PUTMONEY END) AS PUTMONEY FROM HRBUSIDOCITEM WHERE DOCCODE=@DOCCODE GROUP BY DPTID2)A             
            LEFT OUTER JOIN             
            (SELECT DEPARTMENTID,SUM(PUTMONEY) AS SUMPUTMONEY FROM HRPUTMONEYDATA WHERE ISNULL(ISIN,0)=1 GROUP BY DEPARTMENTID)B              
            ON A.DPTID2=B.DEPARTMENTID             
            WHERE A.PUTMONEY>-ISNULL(B.SUMPUTMONEY,0))            
  BEGIN            
   RAISERROR('当前部门奖励总额小于当前奖励金额，请检查！',16,1)            
   RETURN            
  END            
            
            
 INSERT INTO HRPUTMONEYDATA(IKEY,PARENT_IKEY,PERIODID,ATTDATE,COMPANYID,HRROWID,HRCODE,HRNAME,ADMINDPT,DOCCODE,DEPARTMENTID,PUTTYPE,ISIN,PUTMONEY,ITEMNAME,PERIODTYPE,ACTIONDATE)              
 SELECT   HRBUSIDOCITEM.IKEY,PARENT_IKEY,CONVERT(VARCHAR(7),@DOCDATE,120),@DOCDATE,HRBUSIDOCHD.COMPANYID,HRROWID,HRCODE,HRNAME,ADMINDPT,@DOCCODE,HRBUSIDOCITEM.DPTID,PUTTYPE,1,PUTMONEY=(CASE PUTISIN WHEN '罚' THEN -PUTMONEY ELSE PUTMONEY END),'车间奖惩','标准期间',
  
ACTIONDATE            
  FROM HRBUSIDOCHD LEFT OUTER JOIN HRBUSIDOCITEM ON HRBUSIDOCHD.DOCCODE=HRBUSIDOCITEM.DOCCODE            
  WHERE HRBUSIDOCHD.DOCCODE=@DOCCODE            
          
END       
      
SET @RESULT='OK'     